#!/bin/bash

# Copyright 2017 Opera Software AS. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

export CCACHE_SLOPPINESS=time_macros,include_file_mtime,file_macro
export CCACHE_CPP2=yes
